### ISSUE TITLE
Duplicate XML tags in Issue-XML

### ISSUE THREAD

**Issue by logpanic** [VTUL/EzidDOI#12]
EzidExportDom.inc.php is adding a journal, journal_issue, and journal_metadata node for each journal_article node in the Issue-XML creation.

**Comment by ctgraham** [comment]
I have a concern with this.

_Background_: I'd like to eliminate the duplication of code across the datacite / crossref / ezid plugins.  The datacite and crossref plugins manage this awkwardly via symlinks.  That's not possible in an independently packaged plugin, but I think we can do one better.

_General Suggestion_: Let's have the ezid plugin include items such as class/DOIExportDom.inc.php, classes/DOIExportPlugin.inc.php, classes/form/DOIExportSettingsForm.inc.php directly from Crossref.  Then, let's also have EzidExportDom inherit from CrossRefExportDom instead of DOIExportDom.  We'll need to override `_generateDOIdataDom()` to keep the doi_data element sparse, but it can otherwise be a very lightweight class.

_Specific Concern_: Ultimately, if we can do more of this inheritance from the existing Crossref plugin and reduce the duplicated code, we might do well to solve the Issue export outside of EzidExportDom.

I'll try to put up a feature branch on Monday to illustrate what I'm thinking.

**Comment by logpanic** [comment]
I just briefly look through the CrossRefExportDom and it makes sense with what we're trying to do. I think  this issue relates ultimately to issue #6. 

The generated XML for the issue currently has too many journal and journal_issue nodes as well as doi_data nodes. The journal and journal_issue nodes need to only be generated once for when the $object is an issue. 

And since Ezid doesn't support multiple doi_data nodes, as you mentioned, the doi_data node needs to be added when the _generateJournalIssueDom is called and not when the _generateJournalArticleDom is called, when the $object is an issue.

**Comment by ctgraham** [comment]
I'm testing https://github.com/ulsdevteam/EzidDOI/commit/34a71bcb4de5e5548b168ce490fb2cc068c49829 as a start to this.

I'm pretty sure we can get away without duplicates of DOIExportDom, DOIExportPlugin, and DOIExportSettingsForm.  I reduced EzidExportDom to an extension of CrossRefExportDom, and reduced PubObjectCache to be just a stub.

I think I would avoid overriding `CrossRefExportDom::_generateJournalIssueDom()`, since we want this to be called normally from `CrossRefExportDom::_appendArticleXML()`, and this seems to be the only caller for it.

To switch the "Issue" export to be individual exports of the issue and each article in the issue, I think we'll need EzidExportDom to override `CrossRefExportDom::generate()` to ensure that only one object is processed at a time, and then modify `EzidRegisterPlugin::processRegisterObjects()` to iterate serially rather than pass them all at once.

**Comment by ctgraham** [comment]
Alternately, if we wanted to maintain `EzidExportDom::generate()`'s inheritance of `DOIExportDom::generate()`'s allowance for multiple objects in the array, we could just modify `EzidRegisterPlugin::processRegisterObjects()` to call generate normally, but then transform the resulting XML into separate XML files for EZID.  This is probably the better solution, but the overrides I mention above seem quicker.

**Comment by logpanic** [comment]
I see what you're saying, but how will iterating serially solve the problem of where the doi_data is placed? As you mentioned earlier, EZID only allows for one doi_data, and therefore, it doesn't really seem like it supports "batch loading". `CrossRefExportDom::_appendArticleXML()` and the other helper methods it calls append a DOI node to the issue dom (https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/plugins/importexport/crossref/classes/CrossRefExportDom.inc.php#L302-L305) and the article dom (https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/plugins/importexport/crossref/classes/CrossRefExportDom.inc.php#L378-L379). 

It seems like if we wanted to register the Issue with its own DOI and register each article with its own DOI, we would need to parse out each article into its own XML file and send it; also, we'd need to remove the duplicate journal, journal_issue, and journal_metadata nodes associated with each article in the main issue XML file as well as remove the doi_data nodes from each article.

I think my second paragraph is addressing what you mentioned in your second comment. I guess we'd handle removing the duplicate nodes within that transform method you mentioned?

**Comment by ctgraham** [comment]
Yes, to place the doi_data element in the issue, we would need a new private helper method to EzidExportDom.  We still need the code, I just recommend not putting it in _generateJournalIssueDom() because _generateJournalIssueDom won't know if it is being called in support of _appendArticleXML() or if it is being called standalone to create the issue DOI.  Speaking of issue DOIs, [do we know that these are compatible with EZID via the Crossref XML](https://github.com/VTUL/EzidDOI/issues/6#issuecomment-143742626)?

Yes, your [second paragraph](https://github.com/VTUL/EzidDOI/issues/12#issuecomment-143754460) sounds like my [second comment](https://github.com/VTUL/EzidDOI/issues/12#issuecomment-143737166).

I probably won't be much help in either of these options, as Issue DOI registration is not a priority for us.  I'm out of the office for the rest of this week, but what time I do have will be focused on [integration with the Pub ID settings](https://github.com/VTUL/EzidDOI/issues/3) and any general cleanup (such as https://github.com/ulsdevteam/EzidDOI/commit/34a71bcb4de5e5548b168ce490fb2cc068c49829) that assists in that effort.

**Comment by logpanic** [comment]
Fixed with PR #14
